name: itb-kk
services:
  frontend:
    image: wanassanan/itb-kk-frontend:latest
    container_name: itbkk-frontend
    restart: on-failure:5
    networks:
      - frontier

  database:
    image: wanassanan/itb-kk-database:latest
    container_name: itbkk-database
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 20
    networks:
      - backtier
    env_file: ./env.d/env-db
    volumes:
      - ./mysql-datalib:/var/lib/mysql
    ports:
      - 13306:3306

  backend:
    depends_on:
      database:
        condition: service_healthy
    image: wanassanan/itb-kk-backend:latest
    container_name: itbkk-backend
    restart: on-failure:5
    networks:
      - frontier
      - backtier
    env_file: ./env.d/env-be
    volumes:
      - ./attachments-dir:/upload-dir
    ports:
      - 8080:8080

  proxy-server:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    container_name: proxy
    restart: on-failure:5
    networks:
      - frontier
      - proxy-watchtower
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/fullchain.pem:/ssl/fullchain.pem
      - ./ssl/privkey.pem:/ssl/privkey.pem
      - ./ssl/dhparam-2048.pem:/ssl/dhparam-2048.pem
    configs:
      - source: proxy_public_config
        target: /etc/nginx/conf.d/intproj23.conf
      - source: proxy_private_config
        target: /etc/nginx/conf.d/ip23pl1.conf

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: on-failure:5
    networks:
      - proxy-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./env.d/env-watchtower
    command: itbkk-frontend itbkk-backend itbkk-database

networks:
  frontier:
    driver: bridge
  backtier:
    driver: bridge
  proxy-watchtower:
    driver: bridge

configs:
  proxy_public_config:
    file: ./proxy-conf/intproj23.conf
  proxy_private_config:
    file: ./proxy-conf/ip23pl1.conf
