name: Auto deploy infrastructure
run-name: "@${{ github.actor }} was pushed up a new update. Auto deploy start !!"
on:
  workflow_dispatch: 

jobs:
  SSH-update-infra:
    runs-on: ubuntu-latest
    steps:
    - name: execute remote ssh using password
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd INT221/project
          git config --local url."https://${{ secrets.GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
          docker compose down
          git fetch
          git pull origin main
          docker compose up -d
